SistemaViaticos/SistemaGastoviajes/Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaEmpleado;
using System.IO;
using Newtonsoft.Json;
using System.Configuration;

namespace SistemaGastoviajes.Controllers
{
    [Authorize]
    public class CatalogoController : Controller
    {
        // GET: Catalogo
        public ActionResult EstatusCom()
        {
            return View();
        }

        public ActionResult EstatusViajes()
        {
            return View();
        }
        public ActionResult Proyectos()
        {
            return View();
        }
        public ActionResult CuentasContables()
        {
            return View();
        }
        public ActionResult UnidadAdmin()
        {
            return View();
        }
        public ActionResult CentroCostos()
        {
            return View();
        }
        public ActionResult Tipogastos()
        {
            return View();
        }

        public ActionResult Miscuentas()
        {
            return View();
        }





        public ActionResult formapago()
        {
            return View();
        }


        
        [HttpPost]



        public ActionResult Misvia(int id)
        {

            Session["idcuen"] = id;

          //  idm = id;

            return Json(new { data = id }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]



        public ActionResult ImporteViaje(int id)
        {

            Session["importe"] = id;

            //  idm = id;

            return Json(new { data = id }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public JsonResult imagencomprobante(int id)
        {
            bool conversion;

            comprobante_gasto co = new Cn_comprobantegasto().Listarimagen().Where(p => p.id == id).FirstOrDefault();
            string textoBase64 = Cn_recursos.convertirBase64(Path.Combine(co.rutaimagen, co.nombreimagen), out conversion);


            return Json(new
            {
                conversion = conversion,
                textoBase64 = textoBase64,
                extension = Path.GetExtension(co.nombreimagen)
            },
            JsonRequestBehavior.AllowGet
            );





        }

        [HttpGet]

        public JsonResult listacomdegasto()
        {
            int ido;

            ido = Convert.ToInt16(Session["idcuen"]);

            List<comprobante_gasto> olista = new List<comprobante_gasto>();
            olista = new Cn_comprobantegasto().Listacomprobante(ido);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]

        public JsonResult listacontaemple()
        {
            int ido;

            ido = Convert.ToInt16(Session["idcuen"]);

            List<contableempleado> olista = new List<contableempleado>();
            olista = new cn_contableempleado().Listarcontaemple(ido);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]

        public JsonResult listarviaje()
        {
            List<solicitarviaje> olista = new List<solicitarviaje>();
            olista = new cn_solictarviaje().Listar2();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult listacontables()
        {
            int ido;

            ido = Convert.ToInt16(Session["idcuen"]);


            total olista = new cn_contableempleado().Listitacontable(ido);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult sumarcompro()
        {
            int ido;

            ido = Convert.ToInt16(Session["idcuen"]);


            total olista = new Cn_comprobantegasto().sumarcompro(ido);
            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult editavia(solicitarviaje objeto)

        {


            object resultado;
            string Mensaje = string.Empty;

            resultado = new cn_solictarviaje().editaviajesito(objeto, out Mensaje);



            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public JsonResult editacom(comprobante_gasto objeto)

        {


            object resultado;
            string Mensaje = string.Empty;

            resultado = new Cn_comprobantegasto().editarcomprobante(objeto, out Mensaje);



            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult editcomprobante(contableempleado objeto)

        {

            object resultado;
            string Mensaje = string.Empty;

            resultado = new cn_contableempleado().editarcomprobante(objeto, out Mensaje);



            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }

        //proyecto......
        #region Proyecto

        [HttpGet]

        public JsonResult listaproyecto()
        {
            List<proyecto> olista = new List<proyecto>();
            olista = new Cn_proyecto().Listarproyecto2();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult guardarproyecto(proyecto objeto)

        {

            object resultado;
            string Mensaje = string.Empty;
            if (objeto.id == 0)
            {
                resultado = new Cn_proyecto().Registrarproyecto(objeto, out Mensaje);


            }
            else
            {
                resultado = new Cn_proyecto().editarproyecto(objeto, out Mensaje);

            }
            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult eliminarproyecto(int id)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;
            respuesta = new Cn_proyecto().Elimarproyecto(id, out Mensaje);

            return Json(new { resultado = respuesta, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);


        }

        #endregion


        // forma de pago 

        #region

        [HttpGet]

        public JsonResult listaformapago()
        {
            List<formapa> olista = new List<formapa>();
            olista = new cn_formapago().Listarformapago();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult guardarformago(formapa objeto)

        {

            object resultado;
            string Mensaje = string.Empty;
            if (objeto.id == 0)
            {
                resultado = new cn_formapago().Registrarformapago(objeto, out Mensaje);


            }
            else
            {
                resultado = new cn_formapago().editarformapago(objeto, out Mensaje);

            }
            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult eliminarformapago(int id)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;
            respuesta = new cn_formapago().Elimarformapago(id, out Mensaje);

            return Json(new { resultado = respuesta, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        // cuenta centrogastos 

        #region

        [HttpGet]

        public JsonResult listacentrogasto()
        {
            List<centrodecostos> olista = new List<centrodecostos>();
            olista = new Cn_centrocostos().Listarcentrocostos();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult guardarcentrocosto(centrodecostos objeto)

        {

            object resultado;
            string Mensaje = string.Empty;
            if (objeto.id == 0)
            {
                resultado = new Cn_centrocostos().registrarcentrocosto(objeto, out Mensaje);


            }
            else
            {
                resultado = new Cn_centrocostos().editarcentrocosto(objeto, out Mensaje);

            }
            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult eliminarcentrocosto(int id)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;
            respuesta = new Cn_centrocostos().Elimarcentrocosto(id, out Mensaje);

            return Json(new { resultado = respuesta, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);


        }

        #endregion

        //cuenta gastos
        #region

        [HttpGet]

        public JsonResult listagastos()
        {
            List<cuentagastos> olista = new List<cuentagastos>();
            olista = new Cn_cuentagasto().Listargastos();


            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult guardargastos(cuentagastos objeto)

        {

            object resultado;
            string Mensaje = string.Empty;
            if (objeto.idgasto == 0)
            {
                resultado = new Cn_cuentagasto().Registrargastos(objeto, out Mensaje);


            }
            else
            {
                resultado = new Cn_cuentagasto().editargasto(objeto, out Mensaje);

            }
            return Json(new { resultado = resultado, Mensaje = Mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult eliminargasto(int id)
        {
            bool respuesta = false;
            string Mensaje = string.Empty;

SistemaViaticos/SistemaGastoviajes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.SISTEMA DE GASTOS DE VIAJES </title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.dataTables.min.css" />



    @*@ @Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">



    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">SISTEMA_VIATICOS</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!-- <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
          <div class="input-group">
              <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
              <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
          </div>
      </form> -->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!"> <b>@User.Identity.Name</b> </a></li>
                   
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("cerrarsesion","Acceso")">CERRAR SESION</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">CATALOGOS</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-money-check"></i></div>
                            CUENTAS
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("CuentasContables", "Catalogo")">CUENTAS CONTABLES </a>
                                <a class="nav-link" href="@Url.Action("Tipogastos", "Catalogo")"> <div class="sb-nav-link-icon"><i class="fas fa-money-check"></i></div>GASTOS </a>
                                <a class="nav-link" href="@Url.Action("CentroCostos", "Catalogo")">CENTRO DE COSTOS </a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            REPORTES
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("EstatusViajes", "Catalogo")">ESTATUS VIAJES</a>
                                
                                <a class="nav-link" href="@Url.Action("Proyectos", "Catalogo")">PROYECTO </a>

                            </nav>
                        </div>


                        <div class="sb-sidenav-menu-heading">ADMIN</div>
                        <a class="nav-link" href="@Url.Action("UnidadAdmin","Catalogo")">
                            <div class="sb-nav-link-icon"><i class="fas fa-ad"></i></div>
                            UNIDAD ADMINISTRATIVA
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            USUARIOS
                        </a>
                          <a class="nav-link" href="@Url.Action("Index","Home")">
           <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
           INICIO
       </a>  
                        <!--   <div class="sb-sidenav-menu-heading">Addons</div>
    <a class="nav-link" href="charts.html">
        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
        Charts
    </a>
    <a class="nav-link" href="tables.html">
        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
        Tables
    </a>-->
                    </div> 
                    </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()

                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">TANGENTE &copy; TANGENTE INTELIGENTE 2022</div>
                        <div>
                            <a href="#">POLITICA DE PRIVACIDAD</a>
                            &middot;
                            <a href="#">TERMINOS &amp; CONDICIONES</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>




   

    @*@<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
    <li>@Html.ActionLink("Contacto de mis padres", "Contact", "Home")</li>*@
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>